"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const input_vue_vue_type_script_setup_true_lang = require("./src/input.vue.js");
require("vue");
const install = require("../../utils/vue/install.js");
const input = require("./src/input.js");
const WInput = install.withInstall(input_vue_vue_type_script_setup_true_lang.default);
exports.inputProps = input.inputProps;
exports.WInput = WInput;
exports.default = WInput;
