"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const index = require("../components/button/index.js");
const index$1 = require("../components/input/index.js");
const index$2 = require("../components/form/index.js");
const input = require("../components/input/src/input.js");
exports.WButton = index.WButton;
exports.WInput = index$1.WInput;
exports.WForm = index$2.WForm;
exports.inputProps = input.inputProps;
