"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const elementPlus = require("element-plus");
const componentMap = /* @__PURE__ */ new Map();
componentMap.set("Input", { component: elementPlus.ElInput, options: { eventKey: "onInput" } });
componentMap.set("InputNumber", { component: elementPlus.ElInputNumber });
componentMap.set("Select", { component: elementPlus.ElSelect });
componentMap.set("DatePicker", { component: elementPlus.ElDatePicker });
componentMap.set("Switch", { component: elementPlus.ElSwitch });
componentMap.set("Checkbox", { component: elementPlus.ElCheckbox });
exports.componentMap = componentMap;
